package continuedev

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"sigs.k8s.io/yaml"

	"github.com/spxrogers/agentsync/internal/adapter"
	"github.com/spxrogers/agentsync/internal/adapter/claude"
	"github.com/spxrogers/agentsync/internal/source"
)

// Ingest reads Continue's native block files and returns a partial
// source.Canonical. It is the inverse of Render (modulo the documented projected
// loss — command argument-hint/allowed-tools — which Render drops with a report).
func (a *Adapter) Ingest(scope adapter.Scope, project string) (source.Canonical, error) {
	if err := adapter.RequireProjectRoot(scope, project); err != nil {
		return source.Canonical{}, err
	}
	p := ResolvePaths(a.opts.TargetRoot, project, scope == adapter.ScopeProject)
	var c source.Canonical
	warn := a.stderr()

	// MCP from .continue/mcpServers/*.yaml (one or more server entries per block).
	if entries, err := os.ReadDir(p.MCPDir); err == nil {
		for _, e := range entries {
			if e.IsDir() {
				continue
			}
			ext := filepath.Ext(e.Name())
			if ext != ".yaml" && ext != ".yml" && ext != ".json" {
				continue
			}
			data, err := os.ReadFile(filepath.Join(p.MCPDir, e.Name()))
			if err != nil {
				fmt.Fprintf(warn, "warning: skipping MCP block %q: %v\n", e.Name(), err)
				continue
			}
			var block map[string]any
			if err := yaml.Unmarshal(data, &block); err != nil {
				fmt.Fprintf(warn, "warning: skipping MCP block %q: %v\n", e.Name(), err)
				continue
			}
			servers, ok := block["mcpServers"].([]any)
			if !ok {
				continue
			}
			fallbackID := e.Name()[:len(e.Name())-len(ext)]
			for _, raw := range servers {
				srv, ok := raw.(map[string]any)
				if !ok {
					continue
				}
				id := asStr(srv["name"])
				if id == "" {
					id = fallbackID
				}
				// Render emits one <id>.yaml per server, so a captured server
				// whose id differs from its block's filename — or a sibling in a
				// multi-server block — re-applies as a NEW file alongside the
				// original (now-foreign) block, and Continue would load both.
				// Capture it, but tell the user about the duplicate hazard.
				if id != fallbackID || len(servers) > 1 {
					fmt.Fprintf(warn, "warning: MCP server %q in block %q: apply renders one %s.yaml per server; remove the original block after import to avoid duplicate definitions\n", id, e.Name(), id)
				}
				c.MCPServers = append(c.MCPServers, source.MCPServer{ID: id, Server: IngestMCPSpec(srv)})
			}
		}
	}

	// Commands from .continue/prompts/<name>.md (prompt blocks). Continue only
	// treats a prompt as a slash command when `invokable: true`, and Render
	// unconditionally writes invokable prompts — so a non-invokable prompt must
	// NOT be captured as a canonical command (re-applying it would silently
	// convert it into a slash command). Only the canonical-relevant
	// `description` is captured; other keys are dropped with a warning.
	if entries, err := os.ReadDir(p.PromptsDir); err == nil {
		for _, e := range entries {
			if e.IsDir() || filepath.Ext(e.Name()) != ".md" {
				continue
			}
			data, err := os.ReadFile(filepath.Join(p.PromptsDir, e.Name()))
			if err != nil {
				fmt.Fprintf(warn, "warning: skipping command %q: %v\n", e.Name(), err)
				continue
			}
			name := e.Name()[:len(e.Name())-len(".md")]
			fm, body, lenient, err := claude.ParseFrontmatterWithReport(data)
			if err != nil {
				fmt.Fprintf(warn, "warning: skipping command %q: %v\n", name, err)
				continue
			}
			if lenient {
				fmt.Fprintf(warn, "warning: command %q frontmatter is not strict YAML; parsed leniently (consider quoting values containing ': ')\n", name)
			}
			if inv, ok := fm["invokable"].(bool); !ok || !inv {
				fmt.Fprintf(warn, "warning: prompt %q is not invokable (no `invokable: true`); not captured as a slash command\n", name)
				continue
			}
			cf := map[string]any{}
			if d, ok := fm["description"].(string); ok && d != "" {
				cf["description"] = d
			}
			if dropped := droppedPromptKeys(fm); len(dropped) > 0 {
				fmt.Fprintf(warn, "warning: prompt %q frontmatter keys not modeled by agentsync dropped on import: %s\n", name, strings.Join(dropped, ", "))
			}
			c.Commands = append(c.Commands, source.Command{Name: name, Frontmatter: cf, Body: body})
		}
	}

	// Memory from .continue/rules/agentsync.md (the agentsync-owned always-apply
	// rule), captured verbatim.
	if data, err := os.ReadFile(filepath.Join(p.RulesDir, memoryRuleFile)); err == nil {
		c.Memory.Body = source.StripManagedBanner(string(data)) // banner stripped — see claude/ingest.go
	}

	return c, nil
}

// continuePromptModeledKeys are the prompt-block frontmatter keys the canonical
// command round-trip accounts for: `description` is captured, and
// `name`/`invokable` are regenerated by Render. Anything else is dropped on
// import with a warning.
var continuePromptModeledKeys = map[string]bool{"description": true, "name": true, "invokable": true}

// droppedPromptKeys returns the sorted frontmatter keys not modeled by the
// canonical command.
func droppedPromptKeys(fm map[string]any) []string {
	var out []string
	for k := range fm {
		if !continuePromptModeledKeys[k] {
			out = append(out, k)
		}
	}
	sort.Strings(out)
	return out
}

func asStr(v any) string { s, _ := v.(string); return s }

func asStrSlice(v any) []string {
	arr, ok := v.([]any)
	if !ok {
		return nil
	}
	out := make([]string, 0, len(arr))
	for _, x := range arr {
		if s, ok := x.(string); ok {
			out = append(out, s)
		}
	}
	return out
}

func asStrMap(v any) map[string]string {
	m, ok := v.(map[string]any)
	if !ok {
		return nil
	}
	out := make(map[string]string, len(m))
	for k, val := range m {
		if s, ok := val.(string); ok {
			out[k] = s
		}
	}
	return out
}
