package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/pelletier/go-toml/v2"
	"github.com/spf13/cobra"
	"github.com/spxrogers/agentsync/internal/iox"
	"github.com/spxrogers/agentsync/internal/marketplace"
	"github.com/spxrogers/agentsync/internal/paths"
	"github.com/spxrogers/agentsync/internal/state"
	"github.com/spxrogers/agentsync/internal/ui"
)

func newMarketplaceCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "marketplace",
		Short: "manage plugin marketplaces",
		Args:  cobra.NoArgs,
	}
	cmd.AddCommand(
		newMarketplaceAddCmd(),
		newMarketplaceRemoveCmd(),
		newMarketplaceListCmd(),
	)
	strictGroup(cmd)
	markGroupScopeUnaware(cmd, "marketplaces are registered per machine — marketplaces/*.toml and the fetch cache "+
		"live under ~/.agentsync, and a project tree pins plugins rather than registering sources")
	return cmd
}

// marketplaceTOML is the shape of marketplaces/<name>.toml.
type marketplaceTOML struct {
	Marketplace marketplaceTOMLSpec `toml:"marketplace"`
}

// marketplaceTOMLSpec is the CLI's read/write shape for marketplaces/<name>.toml.
// head_sha and name are fetch-CACHE metadata deliberately NOT modeled in the
// canonical source.MarketplaceSpec (issue #171): they are regenerated by this
// command on every fetch (head_sha = the source's git HEAD at fetch time; name =
// the resolved marketplace name), so they are written and read here directly and
// never round-tripped through the canonical model. See source.MarketplaceSpec.
type marketplaceTOMLSpec struct {
	URL               string `toml:"url"`
	Ref               string `toml:"ref,omitempty"`
	DefaultUpdateMode string `toml:"default_update_mode,omitempty"`
	HeadSHA           string `toml:"head_sha,omitempty"`
	Name              string `toml:"name,omitempty"`
}

// ---- add --------------------------------------------------------------------

func newMarketplaceAddCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "add <url-or-path>",
		Short: "fetch a marketplace and register it",
		Args:  cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			home := paths.AgentsyncHome(paths.OSEnv{})
			return withGlobalLock(home, func() error { return marketplaceAddRun(cmd, args) })
		},
	}
}

func marketplaceAddRun(cmd *cobra.Command, args []string) error {
	rawURL := args[0]
	home := paths.AgentsyncHome(paths.OSEnv{})
	p, err := newPrinter(cmd)
	if err != nil {
		return err
	}

	// Build the Source from the raw URL/path argument.
	src, err := parseMarketplaceSource(rawURL)
	if err != nil {
		return err
	}

	stopSpin := p.Spin(fmt.Sprintf("fetching marketplace %s", rawURL))
	mpName, headSHA, err := addMarketplaceSource(home, src, rawURL, p.Warnf)
	stopSpin()
	if err != nil {
		return err
	}
	success(cmd, ui.EmojiSuccess, "added marketplace %s (sha=%s)",
		ui.Sanitize(mpName), truncate(headSHA, 12))
	return nil
}

// addMarketplaceSource fetches src into the marketplace cache, writes
// marketplaces/<name>.toml, and records the fetch in state. It returns the
// resolved marketplace name (the declared name from marketplace.json, falling
// back to a URL-derived slug) and the fetched head SHA. rawURL is the original
// source string stored in the TOML.
//
// It does not print a success line or acquire the global lock — callers do.
// Both `marketplace add` and `import` use it so the two produce byte-identical
// canonical artifacts. warnf is the caller's warning sink (p.Warnf for
// `marketplace add`, importIO.warnf for `import`): the state record is
// best-effort and its only failure mode is invisible otherwise.
func addMarketplaceSource(home string, src marketplace.Source, rawURL string, warnf func(string, ...any)) (mpName, headSHA string, err error) {
	// Derive a slug for the marketplace.
	slug := deriveMarketplaceSlug(rawURL)
	cacheDir := marketplaceCacheDir(home, slug)

	// Fetch into cache.
	fetcher := marketplace.Dispatch(src)
	result, err := fetcher.Fetch(src, cacheDir)
	if err != nil {
		return "", "", fmt.Errorf("fetch marketplace %s: %w", rawURL, err)
	}

	// Read marketplace.json to extract the declared name.
	mpName = slug
	mpJSONPath := filepath.Join(cacheDir, ".claude-plugin", "marketplace.json")
	if data, err := os.ReadFile(mpJSONPath); err == nil {
		var mp marketplace.Marketplace
		if json.Unmarshal(data, &mp) == nil && mp.Name != "" {
			// Only adopt the declared name if it sanitises to something usable;
			// a name like "..." sanitises to "" and would author marketplaces/.toml.
			if s := sanitizeSlug(mp.Name); s != "" {
				mpName = s
			}
		}
	}

	// The URL-derived slug and the declared name differ (the common case for a
	// git marketplace): re-slot the fetched cache under the declared name. Every
	// later lookup derives the cache dir from the name this function goes on to
	// record, so the two MUST agree; a re-slot that fails and is ignored
	// registers a marketplace whose cache nothing can find (#233). Fail the add
	// instead: the TOML and the state record are written below, so an early
	// return leaves nothing half-registered. Both names are sanitizeSlug-clean
	// (one path segment each); reslotMarketplaceCache handles the filesystems
	// that fold their case.
	if mpName != slug {
		newCacheDir := marketplaceCacheDir(home, mpName)
		if err := reslotMarketplaceCache(cacheDir, newCacheDir); err != nil {
			// Discard the fetched tree rather than leave it under the slug: no
			// record points at that directory, `marketplace remove` cannot reach
			// it, and searchAllMarketplaces would still offer it to a bare-id
			// `plugin add` as an unregistered marketplace. Best-effort: a re-run
			// re-fetches into whatever is left and re-slots it.
			_ = os.RemoveAll(cacheDir) //nolint:forbidigo // discards the marketplace fetch cache under .state/cache, not a native destination
			return "", "", fmt.Errorf("register marketplace %q: %w; nothing was written to marketplaces/ "+
				"or the state record — fix the cause and re-run", mpName, err)
		}
	}

	// Write marketplaces/<name>.toml.
	mp := marketplaceTOML{
		Marketplace: marketplaceTOMLSpec{
			URL:               rawURL,
			DefaultUpdateMode: "track",
			HeadSHA:           result.HeadSHA,
			Name:              mpName,
		},
	}
	data, err := toml.Marshal(mp)
	if err != nil {
		return "", "", err
	}
	mpPath := filepath.Join(home, "marketplaces", mpName+".toml")
	if err := iox.AtomicWrite(mpPath, data, 0o644); err != nil {
		return "", "", fmt.Errorf("write %s: %w", mpPath, err)
	}

	// Update state.json so the update command can track fetch timestamps and SHAs.
	//
	// The read guard is load-bearing, not defensive noise: Load already returns a
	// FRESH EMPTY state with no error for an absent file, so a non-nil error here
	// means targets.json exists and could not be read — a refused migration (an
	// ambiguous v1 key, a v2 role violation, a non-UTF-8 key), a permissions
	// problem, corruption. Substituting state.New() there and saving would
	// OVERWRITE targets.json with an empty state, discarding every Files/Keys/
	// Plugins entry and every other marketplace; the next apply would then see no
	// ownership at all and back up every managed destination as a foreign
	// collision. Skipping the record instead costs only a stale fetch timestamp,
	// which the next successful add/update repairs. Mirrors marketplaceRemoveRun.
	statePath := filepath.Join(home, ".state", "targets.json")
	if st, lerr := state.Load(statePath); lerr == nil {
		st.Marketplaces[mpName] = state.Marketplace{
			URL:       rawURL,
			HeadSHA:   result.HeadSHA,
			FetchedAt: time.Now().UTC(),
		}
		_ = state.Save(statePath, st) // best-effort; don't fail add on state write errors
	} else {
		// Skipping the record is right, but doing it SILENTLY is not: the user
		// gets a success line while every other command — status, apply, diff,
		// doctor — is already failing on the same unreadable file, and nothing
		// connects the two. Name the file and the underlying error so the fix is
		// findable; the add itself succeeded, so this is a warning, not an error.
		//
		// sanitizeLines, not a raw %v — the same backstop, and for the same
		// reason, as cli/doctor.go's state-file check: a state.Load failure
		// interpolates map keys read VERBATIM from a targets.json whose own
		// schema-2 remedy invites the user to hand-edit it, and the #93/#171 class
		// is a crafted key repainting the terminal around the success line this
		// warning sits beside.
		//
		// Applied HERE rather than left to the sink, because the two callers do
		// not agree: `marketplace add` passes p.Warnf, which reaches fmt.Fprintf
		// through ui.Fdiagf untouched, while `import` passes importIO.warnf, whose
		// "warning: " line ui.WarnWriter happens to sanitize. One call site covers
		// both without depending on which sink was supplied.
		//
		// migrate already %q-quotes every key, so nothing reaching here today
		// carries a raw escape; this is what keeps that true if a future error
		// constructor forgets. Per line, because the refusal is multi-line and
		// ui.Sanitize STRIPS newlines.
		warnf("marketplace %s was added but not recorded in %s, which could not be read: %s; "+
			"run `agentsync doctor` — the record is restored by the next successful "+
			"`agentsync marketplace add`/`update`", mpName, statePath, sanitizeLines(lerr.Error()))
	}

	return mpName, result.HeadSHA, nil
}

// reslotMarketplaceCache moves a freshly-fetched marketplace cache from the
// URL-derived slug directory to the one named by the marketplace's declared
// name. Both are single segments under .state/cache/marketplaces, so this is a
// same-directory rename.
//
// An EXISTING destination is replaced, not merged (swapDir): it is a stale tree
// from an earlier add of this marketplace — or of another one declaring the same
// name, whose marketplaces/<name>.toml and state record this add overwrites
// regardless, so the cache must follow. os.Rename onto a DIFFERENT existing
// directory fails (on Unix Go refuses it before the syscall, on Windows the
// syscall does; only a case-only alias of the same directory goes through),
// which is why a re-add used to keep the STALE cache and orphan the freshly
// fetched tree under the slug while reporting success (#233).
//
// The move is a plain os.Rename first. That is the whole job when nothing is at
// the destination, and on a case-insensitive filesystem (macOS, Windows) also
// when the destination is this very tree under another spelling — a slug and a
// declared name that differ only in case — because a case-only rename of the
// same directory is accepted. A rename that fails has touched nothing; it goes
// on to the replace only when a DIFFERENT entry (a directory or a symlink) is
// standing at the destination while the fetched tree is still at the source.
// That is decided by stat, not by the error: Linux reports EEXIST for an
// occupied destination, Windows reports access denied, and a missing source or
// a permission failure must never be answered by touching the cache the
// marketplace already has. Lstat, not Stat: a symlink standing at the
// destination is a link to unlink (swapDir removes the link, never what it
// points at), not this tree under another name. A symlink standing at the
// SOURCE is not a fetched tree to move — no fetcher leaves one — and is refused
// before anything moves: the plain rename would otherwise install it, into an
// empty slot, as the registered cache.
//
// Every failure is returned. A replace that fails leaves the destination as it
// was and the source where it was (swapDir puts the old tree back, and names
// where it remains should even that fail), and a re-run re-fetches and
// completes.
func reslotMarketplaceCache(from, to string) error {
	// Belt and braces: the fetch just created `from` under this same parent, so
	// the only way the parent is missing here is a concurrent removal.
	if err := os.MkdirAll(filepath.Dir(to), 0o755); err != nil {
		return fmt.Errorf("prepare marketplace cache dir %s: %w", filepath.Dir(to), err)
	}
	// A link where the fetched tree should be: a rename would install it
	// (pointing anywhere, the destination itself included) as the cache, and a
	// replace would first unlink what the marketplace has. A missing or
	// unreadable source is left to the rename to report.
	if fi, lerr := os.Lstat(from); lerr == nil && fi.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("move marketplace cache %s → %s: the source is a symlink, not a fetched tree", from, to)
	}
	err := os.Rename(from, to) //nolint:forbidigo // moves the marketplace fetch cache under .state/cache, not a native destination
	if err == nil {
		return nil
	}
	fromInfo, ferr := os.Lstat(from)
	toInfo, terr := os.Lstat(to)
	if ferr != nil || terr != nil {
		// No source to move, or nothing standing in the way: the failure is
		// genuine, and the destination is left exactly as it was.
		return fmt.Errorf("move marketplace cache %s → %s: %w", from, to, err)
	}
	if os.SameFile(fromInfo, toInfo) {
		// Identical paths, or an alias the rename above did not resolve: the
		// tree is already where it belongs. Replacing it would delete the fresh
		// tree and then fail to rename what is gone.
		return nil
	}
	if err := swapDir(from, to); err != nil {
		return fmt.Errorf("move marketplace cache %s → %s: %w", from, to, err)
	}
	return nil
}

// ---- remove -----------------------------------------------------------------

func newMarketplaceRemoveCmd() *cobra.Command {
	return &cobra.Command{
		Use:     "remove <name>",
		Aliases: []string{"rm"},
		Short:   "remove a marketplace and its cached files",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			home := paths.AgentsyncHome(paths.OSEnv{})
			return withGlobalLock(home, func() error { return marketplaceRemoveRun(cmd, args) })
		},
	}
}

// marketplaceListHint points users at the command that lists registered
// marketplace names; used in `marketplace remove` error messages.
const marketplaceListHint = "run: agentsync marketplace list to see registered names"

func marketplaceRemoveRun(cmd *cobra.Command, args []string) error {
	name := args[0]
	if err := validateCacheKey("marketplace", name); err != nil {
		return fmt.Errorf("%w; %s", err, marketplaceListHint)
	}
	home := paths.AgentsyncHome(paths.OSEnv{})

	tomlPath := filepath.Join(home, "marketplaces", name+".toml")
	// Removing an unregistered name is a user mistake, not a silent no-op: report
	// it and point at `marketplace list` rather than printing "removed".
	if _, err := os.Stat(tomlPath); err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("marketplace %q is not registered; %s", name, marketplaceListHint)
		}
		return fmt.Errorf("stat %s: %w", tomlPath, err)
	}
	if err := os.Remove(tomlPath); err != nil && !os.IsNotExist(err) { //nolint:forbidigo // removes marketplaces/<name>.toml (canonical source), not a native destination
		return fmt.Errorf("remove %s: %w", tomlPath, err)
	}

	cacheDir := marketplaceCacheDir(home, name)
	if err := os.RemoveAll(cacheDir); err != nil { //nolint:forbidigo // removes the marketplace cache under .state/cache, not a native destination
		return fmt.Errorf("remove cache %s: %w", cacheDir, err)
	}
	// The aside a replace parks the old tree at goes with the cache: every scan
	// skips it, so once the name is gone nothing would ever clear it.
	aside := cacheDir + marketplace.CacheAsideSuffix
	if err := os.RemoveAll(aside); err != nil { //nolint:forbidigo // removes the marketplace cache aside under .state/cache, not a native destination
		return fmt.Errorf("remove cache aside %s: %w", aside, err)
	}

	// Remove from state.json (best-effort). Same rule as addMarketplaceSource:
	// keep an unreadable targets.json rather than replace it with an empty one,
	// but say so — a silent skip leaves a stale marketplace record behind while
	// the success line claims a clean removal.
	statePath := filepath.Join(home, ".state", "targets.json")
	if st, lerr := state.Load(statePath); lerr == nil {
		delete(st.Marketplaces, name)
		_ = state.Save(statePath, st)
	} else {
		// sanitizeLines for the same reason as the add twin above: diag reaches
		// fmt.Fprintf through ui.Fdiagf without sanitizing, and this error
		// interpolates hand-editable targets.json keys.
		diag(cmd, ui.LevelWarn, "marketplace %s was removed but its record remains in %s, "+
			"which could not be read: %s; run `agentsync doctor`", name, statePath, sanitizeLines(lerr.Error()))
	}

	success(cmd, ui.EmojiRemoved, "removed marketplace %s", name)
	return nil
}

// ---- list -------------------------------------------------------------------

func newMarketplaceListCmd() *cobra.Command {
	return &cobra.Command{
		Use:     "list",
		Aliases: []string{"ls"},
		Short:   "list registered marketplaces",
		Args:    cobra.NoArgs,
		RunE:    marketplaceListRun,
	}
}

func marketplaceListRun(cmd *cobra.Command, _ []string) error {
	home := paths.AgentsyncHome(paths.OSEnv{})
	dir := filepath.Join(home, "marketplaces")
	entries, err := os.ReadDir(dir)
	if err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("read %s: %w", dir, err)
	}

	var names []string
	mps := map[string]marketplaceTOMLSpec{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".toml") {
			continue
		}
		name := strings.TrimSuffix(e.Name(), ".toml")
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			continue
		}
		var mp marketplaceTOML
		if err := toml.Unmarshal(data, &mp); err != nil {
			continue
		}
		names = append(names, name)
		mps[name] = mp.Marketplace
	}
	sort.Strings(names)

	if len(names) == 0 {
		fmt.Fprintln(cmd.OutOrStdout(), "(no marketplaces registered; try: agentsync marketplace add <url>)")
		return nil
	}
	for _, name := range names {
		mp := mps[name]
		// url and head_sha are config-derived (marketplaces/<name>.toml, a
		// shareable dotfile) and a TOML basic string can hold ESC — sanitize
		// them like the name column so `marketplace list` can't inject escapes
		// (issue #93/#171).
		fmt.Fprintf(cmd.OutOrStdout(), "%-20s url=%-40s sha=%s\n",
			ui.Sanitize(name), ui.Sanitize(mp.URL), ui.Sanitize(truncate(mp.HeadSHA, 12)))
	}
	return nil
}

// ---- helpers ----------------------------------------------------------------

// registeredMarketplaceNames returns the set of marketplace names registered in
// ~/.agentsync/marketplaces/. Both each TOML's declared `name` field and its
// filename stem map to true, so a native marketplace id matches whichever the
// store recorded. It mirrors how `marketplace list` enumerates the store and
// lets import resolve a plugin's marketplace from agentsync's own store before
// the agent's native config. A missing or unreadable store yields an empty set.
func registeredMarketplaceNames(home string) map[string]bool {
	entries, err := os.ReadDir(filepath.Join(home, "marketplaces"))
	if err != nil {
		return nil
	}
	out := map[string]bool{}
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".toml") {
			continue
		}
		out[strings.TrimSuffix(e.Name(), ".toml")] = true
		data, err := os.ReadFile(filepath.Join(home, "marketplaces", e.Name()))
		if err != nil {
			continue
		}
		var mp marketplaceTOML
		if toml.Unmarshal(data, &mp) == nil && mp.Marketplace.Name != "" {
			out[mp.Marketplace.Name] = true
		}
	}
	return out
}

// parseMarketplaceSource converts a user-provided URL/path string into a Source.
// Handles:
//   - github:owner/repo[@ref]     → github source
//   - https://...                 → url source
//   - file://... or /abs/path     → relative source
//   - ./rel/path                  → relative source
//
// An input that does not match any known form returns an error rather
// than silently degrading to a relative-path copy. The original behaviour
// turned a typo like `gh:obra/superpowers` (should be `github:`) into
// `cp -r ./gh:obra/superpowers ...`, creating an empty marketplace
// cache with no diagnostic. We now refuse and tell the user the
// supported forms.
func parseMarketplaceSource(rawURL string) (marketplace.Source, error) {
	// github: shorthand
	if strings.HasPrefix(rawURL, "github:") {
		rest := strings.TrimPrefix(rawURL, "github:")
		ref := ""
		if idx := strings.Index(rest, "@"); idx >= 0 {
			ref = rest[idx+1:]
			rest = rest[:idx]
		}
		if rest == "" {
			return marketplace.Source{}, fmt.Errorf("github source missing owner/repo: %q", rawURL)
		}
		return marketplace.Source{Kind: "github", Repo: rest, Ref: ref}, nil
	}

	// file:// URL → treat as relative (strip file:// prefix)
	if strings.HasPrefix(rawURL, "file://") {
		return marketplace.Source{Relative: strings.TrimPrefix(rawURL, "file://")}, nil
	}

	// Absolute path or ./relative
	if strings.HasPrefix(rawURL, "/") || strings.HasPrefix(rawURL, "./") || strings.HasPrefix(rawURL, "../") {
		return marketplace.Source{Relative: rawURL}, nil
	}

	// https:// or http:// → url source
	if strings.HasPrefix(rawURL, "https://") || strings.HasPrefix(rawURL, "http://") {
		return marketplace.Source{Kind: "url", URL: rawURL}, nil
	}

	// Existing local path? (covers bare directory names typed without ./)
	if info, err := os.Stat(rawURL); err == nil && info.IsDir() {
		return marketplace.Source{Relative: rawURL}, nil
	}

	return marketplace.Source{}, fmt.Errorf("unrecognised marketplace source %q; supported forms: github:owner/repo[@ref], https://…, file://…, /abs/path, ./rel/path", rawURL)
}

// deriveMarketplaceSlug derives a filesystem-safe slug from a URL or path.
func deriveMarketplaceSlug(rawURL string) string {
	// Strip common prefixes.
	s := rawURL
	for _, pfx := range []string{"https://", "http://", "file://", "github:"} {
		s = strings.TrimPrefix(s, pfx)
	}
	// Strip trailing .git
	s = strings.TrimSuffix(s, ".git")
	// Replace path separators with dashes.
	s = strings.ReplaceAll(s, "/", "-")
	s = strings.ReplaceAll(s, "\\", "-")
	// Strip leading ./ or ../
	s = strings.TrimPrefix(s, ".-")
	s = strings.TrimPrefix(s, "..-")
	// Collapse multiple dashes.
	for strings.Contains(s, "--") {
		s = strings.ReplaceAll(s, "--", "-")
	}
	s = strings.Trim(s, "-")
	// Sanitise FIRST, then fall back: a punctuation-only source (e.g. "...")
	// survives the trim above but sanitises to "", which would otherwise write
	// marketplaces/.toml and a marketplaces/_ cache dir.
	s = sanitizeSlug(s)
	if s == "" {
		s = "marketplace"
	}
	return s
}

// sanitizeSlug makes a string safe for use as a filename.
func sanitizeSlug(s string) string {
	var b strings.Builder
	for _, r := range s {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' || r == '-' || r == '_' {
			b.WriteRune(r)
		} else if r == '/' || r == '.' || r == ' ' {
			b.WriteRune('-')
		}
	}
	result := b.String()
	// Collapse runs of dashes.
	for strings.Contains(result, "--") {
		result = strings.ReplaceAll(result, "--", "-")
	}
	return strings.Trim(result, "-")
}
